language: java
sudo: required

before_install:
  # Install Linuxbrew
  - sh -c "$(curl -fsSL https://raw.githubusercontent.com/Linuxbrew/install/master/install.sh)"
  - test -d ~/.linuxbrew && PATH="$HOME/.linuxbrew/bin:$HOME/.linuxbrew/sbin:$PATH"
  #- test -d /home/linuxbrew/.linuxbrew && PATH="/home/linuxbrew/.linuxbrew/bin:/home/linuxbrew/.linuxbrew/sbin:$PATH"
  #- test -r ~/.bash_profile && echo 'export PATH="$(brew --prefix)/bin:$(brew --prefix)/sbin:$PATH"' >>~/.bash_profile
  #- echo 'export PATH="$(brew --prefix)/bin:$(brew --prefix)/sbin:$PATH"' >>~/.profile

install:
  - brew update
#  - brew tap homebrew/science
#  - brew install blast

script:
  - brew tap mikessh/repseq
#  - travis_wait brew install migec
  - travis_wait brew install vdjtools
  - travis_wait brew install vdjdb
  - travis_wait brew install igblast-linux
  - travis_wait brew install migmap-linux